# Generated by Django 3.2.8 on 2021-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
