# Generated by Django 3.2.8 on 2021-10-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuspagemodel',
            options={'verbose_name_plural': 'messages'},
        ),
    ]
