# Generated by Django 3.2.8 on 2021-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0002_alter_category_position'),
        ('blog_articel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog_category.Category'),
        ),
    ]
