# Generated by Django 3.2.8 on 2021-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(),
        ),
    ]
