# Generated by Django 3.2.8 on 2021-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='subject',
        ),
        migrations.AddField(
            model_name='faqsubject',
            name='fa_question',
            field=models.ManyToManyField(related_name='que_rel_name', to='faq_page.FaqQuestion'),
        ),
    ]
