# Generated by Django 3.2.9 on 2021-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='')),
                ('description1', models.TextField()),
                ('image1', models.ImageField(upload_to='portfolio-image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='portfolio-image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='portfolio-image/')),
                ('description2', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('publish_time', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='p', max_length=1)),
                ('suggest', models.BooleanField(default=False)),
            ],
        ),
    ]
